### ISSUE TITLE
inplace update

### ISSUE THREAD

**Issue by pmwoodward3** [nap/plexcleaner#1]
I love this idea, is there anyway I could do an inplace "cleaning"? Because the idea of moving/copying 13TB of data sounds like a nightmare.

**Comment by nap** [comment]
It does sound pretty bad.

I have not implemented the worker that will copy media file yet. I will include your request.
I plan to have it detect if you are copying on the same or on different filesystem.

The logic will be that: 
 - if you are on the same filesystem it will use "mv"
 - if you are on different filesystem it will use "cp" then on a different scheduler "rm"  the file if it was copied

In theory, If you are telling the app to use the same input and output library, it will create folder in it and "mv" the file in it.

**Comment by pmwoodward3** [comment]
Awesome! Thanks for replying.

Another question (bigger picture) is about what happens after you use plexcleaner. 

After it renames everything, does plex rescan and just rescan everything, or does the sqlite database get auto updated with the newly renamed contents location. Because it would suck for plex to have to regenerate all that content in the database.

Thanks again, really looking forward to trying this out!

**Comment by nap** [comment]
Here's why I make a distinction on mv/cp+rm
You can see that the iNode number remains the same after a mv but after cp it has a new iNode 
You can see that the iNode with mv change when you mv to another FS
```
unary@unary tmp]$ mkdir a b
[unary@unary tmp]$ touch a/file1.txt
[unary@unary tmp]$ touch b/file2.txt
[unary@unary tmp]$ ls -i a/file1.txt
532424 a/file1.txt
[unary@unary tmp]$ mv a/file1.txt b/file2.txt
[unary@unary tmp]$ ls -i b/file2.txt
532424 b/file2.txt
[unary@unary tmp]$ cp b/file2.txt a/file1.txt
[unary@unary tmp]$ ls -i a/file1.txt
532425 a/file1.txt
[unary@unary tmp]$ ls -i b/file2.txt
532424 b/file2.txt
[unary@unary tmp]$ mkdir /mnt/Movies/test
[unary@unary tmp]$ mv b/file2.txt /mnt/Movies/test/file2.txt
[unary@unary tmp]$ ls -i /mnt/Movies/test/file2.txt
66584578 /mnt/Movies/test/file2.txt
```

Regarding your last question:
The app was made in an effort to move away from Plex and use MiniDLNA instead.

If I have some time tonight, I'll check if the database can be updated with the new location of the media without any corruption.

**Comment by pmwoodward3** [comment]
Thanks for the breakdown, I didn't know that.

It wouldn't be terrible if plex had to rebuild the database, because it would ensure that the new database would be working off "prettifed" names so it would be easy to identify the media (being that it was pulled directly from the plex database to begin with).

But ideally it would be amazing for this to update the database with new locations if possible.

**Comment by nap** [comment]
From what I've seen; there's only one place in the database that there's a reference to the path of a media file.

Unless there's some computation on that value to generate some hash; it should not be a problem to update the value.

**Comment by nap** [comment]
Alright, so I did some quick benchmark regarding the copy of file using ```rsync -a```, ```cp```, ```cat a > b```, and ```shutil.move()```.

What I found is that ```cp``` is the fastest, but it only has a ```0.3s``` gain over ```shutil.move()```. It'll be much better/easier to use ```shutil.move()```. I'll be able to implement the feature faster too since ```shutil.move()``` make the distinction between same or different filesystem!

Now for handling the new location of media, well good news, it works without much effort!
